### PR TITLE
Size of the universe

### PR DESCRIPTION
**Pull request by gheorghina**
Review follow-up for issue #1

### CODE REVIEW

**Comment by gheorghina** [comment]
@petrohi - please check this

**Comment by gheorghina** [comment]
@petrohi - I adjusted the implementation to lookup over smaller universes for each group of adjacent cells and not to have to search through the list for indexes

**Comment by petrohi** [comment]
Thanks! Can you add README file that explains how `evolve` works?

**Comment by gheorghina** [comment]
@petrohi - I added a readme with the logic

**Comment by petrohi** [comment]
Thanks!

**Comment by gheorghina** [comment]
@petrohi I also did some layout adjustments to make it look a bit better.
If you are ok with it I will merge the changes and close the item. Thank you!

**Pull request merged**
